# Generated by Django 2.2.7 on 2019-11-15 15:42

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CardType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default='', max_length=6)),
                ('is_archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('STR', 'Text'), ('INT', 'Number'), ('LST', 'List'), ('BOL', 'Boolean'), ('TAG', 'Tag')], default='STR', max_length=3)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheets.Card')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheets.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('score', models.SmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0)),
                ('card', models.ManyToManyField(to='sheets.Card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='cardType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheets.CardType'),
        ),
        migrations.CreateModel(
            name='AnswerTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheets.Answer')),
                ('tag', models.ManyToManyField(to='sheets.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerStr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=1000)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheets.Answer')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerLst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), size=None)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheets.Answer')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerInt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(blank=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheets.Answer')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerBol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField(default=False)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheets.Answer')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheets.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sheets.Record'),
        ),
    ]
